l_english:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 group_armor_title: "Armoured Battalions"
 HAS_ARMIES_WITH_OLD_TEMPLATE: "§RCannot delete this Template because $AMOUNT|H$ Division(s) are transitioning from this template to new one (Waiting to receive equipment matching new template).§!"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC: "Deployment should have at least one order within theatre to be assigned to any group."

#fixed missing article
 CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§GClick§! to set deployment location for this deployment.\n§GRight-click§! to reset location.\n§YThis is a colonial template and can be deployed only in the country of origin!§!"
